version: '3'

services:
  knowquest:
    build: .
    image: knowquest
    environment:
      - MONGODB_URL=${MONGODB_URL}
    ports:
      - '5000:5000'
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/knowquest
    networks:
      - node-network

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - node-network

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
