version: '3.8'

services:
  nodebackend:
    build:
      context: ./backend
    volumes:
      - ./backend:/usr/local/knowquest
      - /usr/local/knowquest/node_modules
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge
